### PR TITLE
Sp 354 configure

### PR DESCRIPTION
**Pull request by apurvapatkar**
- Update Configure command on SubarrayNode to receive JSON for CSP and SDP configuration.
- Implement ConfigureScan command on SDP Subarray leaf node to receive JSON for SDP configuration.
- Implement ConfigureScan command on CSP Subarray leaf node to receive JSON for CSP configuration.

### CODE REVIEW

**Comment by mangeshska** [comment]
Comments on SubArrayNode.Configure implementation:
1.Remove unnecessary print statements that were added for debugging. 
2. change print("Configuration of CSP is done.") to print("CSP Configuration is initiated.")
as this is printed when command is sent out to the CSPsubarrayLeafNode, and not after CSP configuration is completed successfully.
Same applies for SDP and Dish configuration
3.Subarray.Configure command:
Consider asynchronous calling of CSP, SDP and Dish config.
4.Add comments/explanation where nodes are deleted from configuration JSON to tailor it for CSP/SDP/Dish configuration.
5.Track is invoked from SubarrayNode as part of the "Configure" implementation. 
Can this be internally invoked from DishLeafNode as part of its own "Configure" implementation?
5. Consider Adding a differentiator for TANGO specific exceptions.(Not specific to this class, but can be a coding guidelines item)
6. except DevFailed as dev_failed: - Can be useful to mention specific device. For ex. sdpSubarrayLeafNode  
7. The Current implementation does not have rollback strategy in case CSP or SDP configuration fails, as it still proceeds with Dish configuration. Likewise, strategy for Dish failures can be worked out.

**Comment by apurvapatkar** [comment]
> Comments on SubArrayNode.Configure implementation:
> 1.Remove unnecessary print statements that were added for debugging.
> 2. change print("Configuration of CSP is done.") to print("CSP Configuration is initiated.")
> as this is printed when command is sent out to the CSPsubarrayLeafNode, and not after CSP configuration is completed successfully.
> Same applies for SDP and Dish configuration
> 3.Subarray.Configure command:
> Consider asynchronous calling of CSP, SDP and Dish config.
> 4.Add comments/explanation where nodes are deleted from configuration JSON to tailor it for CSP/SDP/Dish configuration.
> 5.Track is invoked from SubarrayNode as part of the "Configure" implementation.
> Can this be internally invoked from DishLeafNode as part of its own "Configure" implementation?
> 5. Consider Adding a differentiator for TANGO specific exceptions.(Not specific to this class, but can be a coding guidelines item)
> 6. except DevFailed as dev_failed: - Can be useful to mention specific device. For ex. sdpSubarrayLeafNode
> 7. The Current implementation does not have rollback strategy in case CSP or SDP configuration fails, as it still proceeds with Dish configuration. Likewise, strategy for Dish failures can be worked out.

**Comment by apurvapatkar** [comment]
Comments on SubArrayNode.Configure implementation:
1.Remove unnecessary print statements that were added for debugging. - **Done**
2. change print("Configuration of CSP is done.") to print("CSP Configuration is initiated.") 
as this is printed when command is sent out to the CSPsubarrayLeafNode, and not after CSP configuration is completed successfully. - **Done**
Same applies for SDP and Dish configuration
4.Add comments/explanation where nodes are deleted from configuration JSON to tailor it for CSP/SDP/Dish configuration. - **Done**
Other comments will be resolved as a part of different stories.

The commit id is: [9b35db638310cea3e79223d137da717a19edf2c8](https://github.com/ska-telescope/tmc-prototype/commit/9b35db638310cea3e79223d137da717a19edf2c8)

**Comment by mangeshska** [comment]
OK

**Pull request merged**
